#!/usr/bin/env bash
# This bash Script displays the number from 1 to 100
# if the number is multiple of 3 and 5, it displays fizzbuzz
# if the number is multiple of 3 it displays Fizz
# if the number is a multiple of 5 it displays Buzz
# Otherwise it displays the number

for i in $(seq 1 100)
do
	if [ $(("$i" % 5)) -eq 0 ] && [ $(("$i" % 3 )) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $(("$i" % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $(("$i" % 3)) -eq 0 ]
	then
		echo "Fizz"
	else
		echo "$i"
	fi
done
			
