#!/usr/bin/env bash
# This Script makes use of "IFS" and a while loop to
# display a string while reading some data from /etc/passwd
# file.

while IFS=: read -r username password uid gid gecos home shell;
do
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $gecos"
done < /etc/passwd
