#!/usr/bin/env bash
# This Script makes use of "IFS" and a while loop to
# display a string while reading some data from /etc/passwd
# file.

while IFS= read -r line;
do
	user=$(echo "$line" | cut -d":" -f1)
	group_id=$(echo "$line" | cut -d":" -f3)
	home=$(echo "$line" | cut -d":" -f6)
	shell=$(echo "$line" | cut -d":" -f7)
	uid=$(echo "$line" | cut -d":" -f3)
	passcode=$(echo "$line" | cut -d":" -f2)
	user_info=$(echo "$line" | cut -d":" -f5)


	echo "The user $user is part of the $group_id gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passcode, more info about the user here: $user_info"
done < /etc/passwd
