#!/usr/bin/env bash
# This Displays "Best School" 10 times but for the 9th Iteration
# it displays "Best School" and "Hi" on a new line

i=0
while [ $i -lt 10 ];
do
	if [ $i -eq 8 ]
	then
		echo -e "Best School\nHi"
	else
		echo "Best School"
	fi
	((i++))
done
