#!/usr/bin/env bash
# This bash script Displays numbers from 1 to 20 and:
# Displays "4" and then "bad luck from China" for the 4th iteration
# Displays "9" and then "bad luck from Japan" for the 9th iteration
# Displays "17" and then "bad luck from Italy" for the 17th iteration

i=1
while [ $i -le 20 ]
do
	case $i in
		4)
			echo -e "4\nbad luck from China";;
		9)
			echo -e "9\nbad luck from Japan";;
		17)
			echo -e "17\nbad luck from Italy";;
		*)
			echo $i
	esac
	((i++))
done
